apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: pgdb
spec:
  selector:
    app: pgdb
  ports:
  - port: 5432
    name: pgdb-port
    targetPort: 5432
  - port: 5050
    name: pgadmin-port
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pg-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /pgadmin
        backend:
          service:
            name: pg-service
            port:
              number: 80