apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-sfs
spec:
  selector:
    matchLabels:
      app: pgdb
  serviceName: pg-service
  replicas: 1
  # revisionHistoryLimit: 1
  minReadySeconds: 60 # by default is 0
  template:   # template of a pod in the statefulset
    metadata:
      labels:
        app: pgdb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgis  # i can select any name here based on the container
        image: postgis/postgis:15-3.3
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-data
          mountPath: /data
        env:
        - name: POSTGRES_USER
          value: unifier
        - name: POSTGRES_PASSWORD
          value: unifier
        - name: POSTGRES_DB
          value: unified-db
        - name: PGDATA
          value: /data/pgdata
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
          - containerPort: 80
            name: pdadmin
        env:
          - name: "PGADMIN_DEFAULT_PASSWORD"
            value: "pgadmin"
          - name: "PGADMIN_DEFAULT_EMAIL"
            value: "pgadmin@slb.com"
          - name: "PGADMIN_SERVER_JSON"
            value: '{"host": "postgis", "port": 5432, "username": "unifier", "password": "unifier", "sslmode": "prefer", "db": "unified-db"}'
        volumeMounts:
          - mountPath: /var/lib/pgadmin/server.json
            # subPath: server.json
            name: pgadmin-config
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
  # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: pg-admin
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 0.25Gi
  