apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-sfs
spec:
  selector:
    matchLabels:
      app: pgdb
  serviceName: pg-service
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 60 # by default is 0
  template:   # template of a pod in the statefulset
    metadata:
      labels:
        app: pgdb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgis  # i can select any name here based on the container
        image: postgis/postgis:15-3.3
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-data
          mountPath: /data
        # env from configmap
        envFrom:
          - configMapRef:
              name: pg-db-config
      - name: pgadmin
        image: dpage/pgadmin4
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
          - containerPort: 80
            name: pgadmin
        # env from configmap
        envFrom:
          - configMapRef:
              name: pgadmin-config
        volumeMounts:
          - name: pg-admin
            mountPath: /data/pgadmin
  # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: pg-admin
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 0.25Gi
  